{
 "title": "Hasura",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Requests per Second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hasura_graphql_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Responses (24h)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by() (hasura_graphql_requests_total{response_status=\"failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(hasura_cache_request_count[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(hasura_cache_request_count{status=\"hit\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(hasura_cache_request_count{status=\"miss\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit/Miss Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hasura_cache_request_count{status=\"hit\"})/sum(hasura_cache_request_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Service Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(source_name) (hasura_postgres_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recent Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "service": "Hasura GraphQL Engine" }
   ]
  },
  {
   "title": "GraphQL Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "hasura_graphql_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PostgreSQL Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "hasura_postgres_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "hasura_active_subscriptions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request/Response bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "hasura_action_request_bytes_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "hasura_action_response_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution Time (Slow Queries)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "hasura_graphql_execution_time_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Map",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    { "expr": "hasura_graphql_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "__auto" }
   ]
  }
 ]
}