-- Create the bank database
CREATE DATABASE IF NOT EXISTS BANK_DB;

-- Use the bank database
USE DATABASE BANK_DB;

-- Create a table for customer data
CREATE TABLE IF NOT EXISTS CUSTOMERS (
   CUSTOMER_ID INT,
   NAME VARCHAR(50),
   ADDRESS VARCHAR(100),
   CONTACT_DETAILS VARCHAR(100),
   IDENTIFICATION_DOCUMENTS VARCHAR(100),
   ACCOUNT_BALANCE DECIMAL(10,2),
   ACCOUNT_HISTORY VARCHAR(1000),
   CREDIT_SCORE INT
);

-- Create a table for financial data
CREATE TABLE IF NOT EXISTS FINANCIAL_DATA (
   TRANSACTION_ID INT,
   ACCOUNT_ID INT,
   TRANSACTION_DATE TIMESTAMP_NTZ,
   TRANSACTION_TYPE VARCHAR(50),
   AMOUNT DECIMAL(10,2),
   DESCRIPTION VARCHAR(1000)
);

-- Create a table for operational data
CREATE TABLE IF NOT EXISTS OPERATIONAL_DATA (
   ID INT,
   CUSTOMER_ID INT,
   ATM_USAGE VARCHAR(50),
   BRANCH_ACTIVITY VARCHAR(50),
   CUSTOMER_SERVICE_INTERACTIONS VARCHAR(1000)
);

-- Create a table for risk and compliance data
CREATE TABLE IF NOT EXISTS RISK_COMPLIANCE_DATA (
   ID INT,
   TRANSACTION_MONITORING_DATA VARCHAR(1000),
   COMPLIANCE_AUDIT_DATA VARCHAR(1000),
   FRAUD_DETECTION_DATA VARCHAR(1000)
);

-- Create a table for marketing and sales data
CREATE TABLE IF NOT EXISTS MARKETING_SALES_DATA (
   ID INT,
   CUSTOMER_PREFERENCES VARCHAR(1000),
   CUSTOMER_BEHAVIOR VARCHAR(1000),
   SALES_DATA VARCHAR(1000)
);

-- Create a table for clickstream data
CREATE TABLE IF NOT EXISTS CLICKSTREAM_DATA (
   USER_ID INT,
   SESSION_ID INT,
   EVENT_TIME TIMESTAMP_NTZ DEFAULT DATEADD('SECOND', ABS(MOD(RANDOM(), 2592000)), '2023-04-06 00:00:00'),
   URL VARCHAR(1000),
   REFERRER VARCHAR(1000),
   EVENT_TYPE VARCHAR(50),
   DEVICE_TYPE VARCHAR(50),
   BROWSER_TYPE VARCHAR(50),
   USER_IP VARCHAR(50),
   LOCATION VARCHAR(100)
);

-- Make CUSTOMER_ID unique and primary key
ALTER TABLE CUSTOMERS
ADD CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY (CUSTOMER_ID);

-- Make CUSTOMER_ID unique and primary key
ALTER TABLE OPERATIONAL_DATA
ADD CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY (CUSTOMER_ID);

-- Make CUSTOMER_ID unique and primary key
ALTER TABLE CLICKSTREAM_DATA
ADD CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY (USER_ID);


ALTER TABLE CLICKSTREAM_DATA
ADD CONSTRAINT FK_CLICK_USER_CUST_ID
FOREIGN KEY (user_id) REFERENCES CUSTOMERS(CUSTOMER_ID);

ALTER TABLE OPERATIONAL_DATA
ADD CONSTRAINT FK_OPER_CUST_CUST_ID
FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(CUSTOMER_ID);

SELECT *
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS;
