FROM node:latest AS build
WORKDIR /build

COPY ./package.json package.json
COPY ./package-lock.json package-lock.json
RUN npm ci

COPY ./public/ public
COPY ./src/ src
COPY ./babel-plugin-macros.config.js babel-plugin-macros.config.js
COPY ./example.env .env

EXPOSE 3000

CMD ["npm", "start"]